# Generated by Django 5.2.17 on 2026-08-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('icon', 'Ícono'), ('image', 'Imagen'), ('font', 'Tipografía')], max_length=24)),
                ('file', models.FileField(upload_to='official-assets/')),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('usage_rules', models.JSONField(default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
