# Generated by Django 5.2.17 on 2026-08-06 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('reference_type', models.CharField(choices=[('approved_base', 'Base aprobada'), ('inspiration', 'Inspiración')], default='inspiration', max_length=24)),
                ('approval_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('archived', 'Archivada')], default='pending', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='artwork-references/')),
                ('source_url', models.URLField(blank=True)),
                ('source_folder_url', models.URLField(blank=True)),
                ('source_file_name', models.CharField(blank=True, max_length=220)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('brand_scope', models.CharField(default='international-house', max_length=120)),
                ('country', models.CharField(blank=True, max_length=4)),
                ('product_slug', models.CharField(blank=True, max_length=80)),
                ('format', models.CharField(blank=True, max_length=24)),
                ('tags', models.JSONField(default=list)),
                ('usage_notes', models.TextField(blank=True)),
                ('provenance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
