# Generated by Django 5.2.17 on 2026-08-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_artworkreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkreference',
            name='repository_path',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
