# Generated by Django 5.2.17 on 2026-08-07 01:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_artworkreference_repository_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='uploaded-logos/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'ai', 'eps', 'pdf'])])),
                ('name', models.CharField(max_length=180)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('logo_type', models.CharField(choices=[('partner', 'Partner'), ('branch', 'Sede'), ('product', 'Producto'), ('school', 'Escuela asociada'), ('other', 'Otro')], default='other', max_length=24)),
                ('variant', models.CharField(default='color', max_length=24)),
                ('usage_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_catalog', 'Pendiente de catálogo'), ('available', 'Disponible para briefs'), ('promoted_official', 'Promovido a oficial'), ('archived', 'Archivado')], default='pending_catalog', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_logos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
