# Generated by Django 5.2.17 on 2026-08-15 21:09

import assets.storage_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_uploadedlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedlogo',
            name='file',
            field=models.FileField(upload_to=assets.storage_paths.uploaded_logo_path, validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'ai', 'eps', 'pdf'])]),
        ),
    ]
