# Generated by Django 5.2.17 on 2026-08-05 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('passed', 'Aprobado'), ('failed', 'Fallido')], default='pending', max_length=16)),
                ('checks', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('design_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='designs.designversion')),
            ],
        ),
    ]
