# Generated by Django 5.2.17 on 2026-08-05 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='design', to='briefs.designbrief')),
            ],
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('template_key', models.CharField(max_length=120)),
                ('render_data', models.JSONField(default=dict)),
                ('asset_refs', models.JSONField(default=list)),
                ('validation_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='designs.design')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='design',
            name='approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_for', to='designs.designversion'),
        ),
        migrations.AddConstraint(
            model_name='designversion',
            constraint=models.UniqueConstraint(fields=('design', 'number'), name='unique_design_version'),
        ),
    ]
