# Generated by Django 5.2.17 on 2026-08-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='test_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designversion',
            name='claude_review',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='designversion',
            name='claude_review_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pass', 'Correcto'), ('needs_changes', 'Requiere cambios')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('self_review', 'Revision de Claude'), ('test_ready', 'Listo para prueba'), ('revision_requested', 'Cambios solicitados'), ('archived', 'Archivado')], default='draft', max_length=24),
        ),
    ]
