# Generated by Django 5.2.17 on 2026-08-14 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0004_passwordresettoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HubIdentityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("linked", "Existing user linked"),
                            ("provisioned", "User provisioned"),
                            ("login_success", "Login succeeded"),
                            ("login_denied", "Login denied"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("success", "Success"), ("denied", "Denied")], max_length=16
                    ),
                ),
                ("hub_subject", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hub_identity_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="HubIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hub_subject", models.CharField(editable=False, max_length=255, unique=True)),
                ("initial_email", models.EmailField(editable=False, max_length=254, unique=True)),
                ("email_snapshot", models.EmailField(max_length=254)),
                (
                    "link_source",
                    models.CharField(
                        choices=[
                            ("linked_existing", "Linked existing user"),
                            ("provisioned", "Provisioned least-privilege user"),
                        ],
                        max_length=32,
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("last_authenticated_at", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hub_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["hub_subject"],
                "indexes": [
                    models.Index(
                        fields=["last_authenticated_at"], name="security_hu_last_au_ae2171_idx"
                    )
                ],
            },
        ),
    ]
