# Generated by Django 5.2.17 on 2026-08-15 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, unique=True)),
                ('suppressed', models.BooleanField(db_index=True, default=False)),
                ('suppression_reason', models.CharField(blank=True, max_length=64)),
                ('spam_complaint', models.BooleanField(default=False)),
                ('provider_changed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['recipient'],
            },
        ),
        migrations.CreateModel(
            name='TransactionalEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('message_stream', models.CharField(max_length=64)),
                ('tag', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('submitting', 'Submitting'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('spam_complaint', 'Spam complaint'), ('suppressed', 'Suppressed'), ('reactivated', 'Reactivated'), ('failed', 'Failed')], db_index=True, default='submitting', max_length=32)),
                ('failure_category', models.CharField(blank=True, max_length=64)),
                ('bounce_type', models.CharField(blank=True, max_length=64)),
                ('bounce_type_code', models.PositiveIntegerField(blank=True, null=True)),
                ('safe_reason', models.CharField(blank=True, max_length=500)),
                ('suppressed', models.BooleanField(default=False)),
                ('spam_complaint', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_reset_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_delivery', to='security.passwordresettoken')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactional_email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PostmarkWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_event_id', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(choices=[('Delivery', 'Delivery'), ('Bounce', 'Bounce'), ('SpamComplaint', 'Spam complaint'), ('SubscriptionChange', 'Subscription change')], db_index=True, max_length=32)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('message_stream', models.CharField(blank=True, max_length=64)),
                ('classification', models.CharField(blank=True, max_length=64)),
                ('safe_detail', models.CharField(blank=True, max_length=500)),
                ('suppress_sending', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_events', to='security.transactionalemaildelivery')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
