# Generated by Django 5.2.17 on 2026-08-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_emailrecipientstate_transactionalemaildelivery_and_more'),
        ('security', '0005_hubidentityevent_hubidentity'),
    ]

    operations = [
    ]
