# Generated by Django 5.2.17 on 2026-08-05 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo para generar'), ('in_review', 'En revisión'), ('completed', 'Completado')], default='draft', max_length=24)),
                ('format', models.CharField(choices=[('square', 'Post cuadrado'), ('story', 'Historia'), ('portrait', 'Post vertical')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('audience', models.TextField()),
                ('objective', models.TextField()),
                ('requested_message', models.TextField(blank=True)),
                ('source_references', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.branch')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaign')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
