# Generated by Django 5.2.17 on 2026-08-07 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designbrief',
            name='additional_logo_keys',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='brand_logo_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='brief_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='channel',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='country',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_briefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='language',
            field=models.CharField(default='es', max_length=12),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='product_slug',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='visual_reference_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='designbrief',
            name='format',
            field=models.CharField(choices=[('square', 'Post cuadrado'), ('story', 'Historia'), ('portrait', 'Post vertical'), ('reel', 'Reel'), ('carousel', 'Carrusel'), ('banner', 'Banner'), ('html', 'HTML'), ('svg', 'SVG')], max_length=16),
        ),
        migrations.CreateModel(
            name='BriefReferenceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='brief-references/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_uploads', to='briefs.designbrief')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brief_reference_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
