# Generated by Django 5.2.17 on 2026-08-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0003_designbrief_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='designbrief',
            name='generated_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='designbrief',
            name='prompt_source',
            field=models.CharField(blank=True, choices=[('ai', 'IA'), ('manual', 'Manual'), ('ai_edited', 'IA editada')], default='', max_length=16),
        ),
    ]
