# Generated by Django 5.2.17 on 2026-08-15 21:09

import briefs.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0004_designbrief_generated_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefreferenceupload',
            name='file',
            field=models.FileField(upload_to=briefs.storage_paths.brief_reference_path),
        ),
    ]
