# Generated by Django 5.2.17 on 2026-08-07 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefs', '0002_designbrief_additional_logo_keys_and_more'),
        ('campaigns', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('renderer_family', models.CharField(choices=[('html-svg', 'HTML/SVG'), ('email-html', 'Email HTML'), ('document', 'Documento')], max_length=32)),
                ('channel', models.CharField(max_length=40)),
                ('schema_version', models.CharField(default='1.0.0', max_length=24)),
                ('supported_formats', models.JSONField(default=list)),
                ('priority_product_slugs', models.JSONField(default=list)),
                ('product_scope', models.CharField(default='all_catalog', max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('product_slugs', models.JSONField(default=list)),
                ('brief_context', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo para producción'), ('in_review', 'En revisión'), ('completed', 'Completado')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.branch')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_bundles', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='materials.materialtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_key', models.SlugField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('brief', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='material_bundle_item', to='briefs.designbrief')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.materialbundle')),
            ],
            options={
                'ordering': ['sort_order', 'deliverable_key'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=24)),
                ('dimensions', models.JSONField(default=dict)),
                ('output_formats', models.JSONField(default=list)),
                ('required_fields', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='materials.materialtype')),
            ],
            options={
                'ordering': ['key', '-version'],
            },
        ),
    ]
