# Generated by Django 5.2 on 2026-08-10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0007_school_formal_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("ih", "International House"), ("ielts", "IELTS")],
                        max_length=12,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=8)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("foto_perfil", "Foto de perfil"),
                            ("background_computadora", "Fondo para computadora"),
                            ("background_celular", "Fondo para celular"),
                            ("zoom_background", "Fondo de Zoom"),
                            ("firma_electronica", "Firma electrónica"),
                            ("banner_linkedin", "Banner de LinkedIn"),
                            ("template_ppt", "Template de PowerPoint"),
                        ],
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(max_length=180)),
                (
                    "file",
                    models.FileField(
                        upload_to="marketing-assets/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "webp",
                                    "pdf",
                                    "ppt",
                                    "pptx",
                                ]
                            )
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketing_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["brand", "country", "category", "label"]},
        )
    ]
