# Generated by Django 5.2.17 on 2026-08-10 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_marketingasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingasset',
            name='file',
            field=models.FileField(upload_to='marketing-assets/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'pdf', 'ppt', 'pptx', 'docx'])]),
        ),
    ]
