# Generated by Django 5.2.17 on 2026-08-15 21:09

import django.core.validators
import materials.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_marketingasset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingasset',
            name='file',
            field=models.FileField(upload_to=materials.storage_paths.marketing_asset_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'pdf', 'ppt', 'pptx', 'docx'])]),
        ),
    ]
